# Generated by Django 5.1.7 on 2025-04-19 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField(blank=True, null=True)),
                ('course_code', models.CharField(blank=True, max_length=255, null=True)),
                ('course_name', models.CharField(blank=True, max_length=255, null=True)),
                ('question_text', models.TextField()),
                ('latex_equation', models.TextField(blank=True, null=True)),
                ('option1', models.CharField(default='Option A', max_length=255)),
                ('option2', models.CharField(default='Option B', max_length=255)),
                ('option3', models.CharField(default='Option C', max_length=255)),
                ('option4', models.CharField(default='Option D', max_length=255)),
                ('correct_answer', models.CharField(default='Option 1', max_length=255)),
                ('user_c_answer', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.IntegerField(default=1)),
                ('unit_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='Unknown', max_length=255, null=True, unique=True)),
                ('email', models.EmailField(default='Unknown', max_length=254, unique=True)),
                ('password', models.CharField(default='Unknown', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('course_code', models.CharField(default='123451', max_length=50, unique=True)),
                ('exam_type', models.CharField(choices=[('periodic', 'Periodic Test (30 Marks)'), ('final', 'Final Exam (70 Marks)')], max_length=10)),
                ('num_units', models.IntegerField()),
                ('question_sheet', models.JSONField()),
                ('total_questions', models.IntegerField(default=0)),
                ('total_marks', models.IntegerField(default=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('marks_per_unit', models.JSONField(default=list)),
                ('max_mark', models.IntegerField(default=1)),
                ('exam_duration_hours', models.IntegerField(default=1)),
                ('exam_duration_minutes', models.IntegerField(default=0)),
                ('question_per_unit', models.JSONField(default=dict)),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default='123451', max_length=50)),
                ('year', models.CharField(choices=[('1st Year', '1st Year'), ('2nd Year', '2nd Year'), ('3rd Year', '3rd Year')], default='first', max_length=10)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(choices=[('Computer Technology', 'Computer Technology'), ('Information Technology', 'Information Technology'), ('Electronics', 'Electronics'), ('Mechanical', 'Mechanical'), ('Civil', 'Civil')], default='IF', max_length=50)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('attendance_status', models.BooleanField(default=True)),
                ('has_attempted_exam', models.BooleanField(default=False)),
                ('time_remaining', models.IntegerField(default=0)),
                ('exam_start_time', models.DateTimeField(blank=True, null=True)),
                ('registered_courses', models.ManyToManyField(related_name='students', to='faculty.course')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('percentage', models.FloatField(default=0.0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='faculty.examspecification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.student')),
            ],
        ),
    ]
