# Generated by Django 5.1.6 on 2025-04-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='time_remaining',
            field=models.IntegerField(default=0),
        ),
    ]
