# Generated by Django 5.1.6 on 2025-04-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_alter_student_time_remaining'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='attendance_status',
            field=models.BooleanField(default=True),
        ),
    ]
