# Generated by Django 5.1.6 on 2025-04-11 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0003_student_attendance_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examspecification',
            old_name='questions_per_unit',
            new_name='question_sheet',
        ),
    ]
