# Generated by Django 5.1.6 on 2025-04-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0004_rename_questions_per_unit_examspecification_question_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='examspecification',
            name='questions_per_unit',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
