# Generated by Django 5.1.7 on 2025-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_examspecification_questions_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examspecification',
            name='questions_per_unit',
            field=models.IntegerField(default=0),
        ),
    ]
