# Generated by Django 5.1.7 on 2025-04-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0006_alter_examspecification_questions_per_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examspecification',
            name='questions_per_unit',
        ),
        migrations.AddField(
            model_name='examspecification',
            name='question_per_unit',
            field=models.JSONField(default=dict),
        ),
    ]
